import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Provider from "@/components/provider/Provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "@/components/layout/Footer";

// Lato font config
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // চাইলে weight যোগ করতে পারো
  variable: "--font-lato", // css variable name
});

export const metadata: Metadata = {
  title: "ShibuHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} antialiased`}>
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
