import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider/Provider";
import { Toaster } from "sonner";
import AuthProvider from "@/components/context/AuthProvider";
import ProtectedRoute from "@/components/layout/ProtectedRoute";

// Lato font config
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "ShibuHub",
  description: "Generated by Shawon Mondol Shibu",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} antialiased`}>
        <AuthProvider>
            <Provider>{children}</Provider>
        </AuthProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
