import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Provider from "@/components/provider/Provider";

// Lato font config
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});



export const metadata: Metadata = {
  title: `ShibuHub-Dashboard`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <main className={`${lato.variable} antialiased`}>
      <Provider>
        

            {children}
      </Provider>
    </main>
  );
}
