import type { Metadata } from "next";
import Provider from "@/components/provider/Provider";

export const metadata: Metadata = {
  title: `ShibuHub-Dashboard`,
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="antialiased" suppressHydrationWarning>
      <Provider>{children}</Provider>
    </main>
  );
}
