import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../globals.css";
import Provider from "@/components/provider/Provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";

// Lato font config
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // চাইলে weight যোগ করতে পারো
  variable: "--font-lato", // css variable name
});

export const metadata: Metadata = {
  title: "ShibuHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={`${lato.variable} antialiased`}>
      <Provider>
        <SidebarProvider
          style={
            {
              "--sidebar-width": "calc(var(--spacing) * 72)",
              "--header-height": "calc(var(--spacing) * 12)",
            } as React.CSSProperties
          }
        >
          <AppSidebar variant="inset" />
          <SidebarInset>
            <SiteHeader />
            {children}
          </SidebarInset>
        </SidebarProvider>
      </Provider>
    </main>
  );
}
